/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EducationEntry = IDL.Record({
  'school' : IDL.Text,
  'year' : IDL.Text,
  'description' : IDL.Text,
  'degree' : IDL.Text,
});
export const ExperienceEntry = IDL.Record({
  'role' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'dateRange' : IDL.Text,
});
export const CV = IDL.Record({
  'education' : IDL.Vec(EducationEntry),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'experience' : IDL.Vec(ExperienceEntry),
  'summary' : IDL.Text,
  'selectedTemplate' : IDL.Nat,
  'jobTitle' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCV' : IDL.Func([], [IDL.Opt(CV)], ['query']),
  'getSelectedTemplate' : IDL.Func([], [IDL.Nat], ['query']),
  'selectTemplate' : IDL.Func([IDL.Nat], [], []),
  'updateCV' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(EducationEntry),
        IDL.Vec(ExperienceEntry),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EducationEntry = IDL.Record({
    'school' : IDL.Text,
    'year' : IDL.Text,
    'description' : IDL.Text,
    'degree' : IDL.Text,
  });
  const ExperienceEntry = IDL.Record({
    'role' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'dateRange' : IDL.Text,
  });
  const CV = IDL.Record({
    'education' : IDL.Vec(EducationEntry),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'experience' : IDL.Vec(ExperienceEntry),
    'summary' : IDL.Text,
    'selectedTemplate' : IDL.Nat,
    'jobTitle' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getCV' : IDL.Func([], [IDL.Opt(CV)], ['query']),
    'getSelectedTemplate' : IDL.Func([], [IDL.Nat], ['query']),
    'selectTemplate' : IDL.Func([IDL.Nat], [], []),
    'updateCV' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(EducationEntry),
          IDL.Vec(ExperienceEntry),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };